### ISSUE TITLE
TypeError: require(...).requirePackage is not a function

### ISSUE THREAD

**Issue by yesmeck** [bevry/errlop#2] opened 2018-12-28 15:58 UTC
My app works fine a hour ago, but after a refresh npm install, I got this error, and I found that `errlop` was just released a new version. So I guess the new version of errlop has some breaking changes.

```
/Users/meck/Workspace/app/node_modules/errlop/index.js:4
module.exports = require('editions').requirePackage(__dirname, require)
                                     ^

TypeError: require(...).requirePackage is not a function
    at Object.<anonymous> (/Users/meck/Workspace/app/node_modules/errlop/index.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/meck/Workspace/dchain-frontend/node_modules/editions/edition-node-0.8/index.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
error Command failed with exit code 1.
```

**Comment by matthewp** [comment] 2018-12-28 16:00
Same here. I see that these are circular dependencies. Is this a new thing?

**Comment by jlandersen** [comment] 2018-12-28 16:00
Broke several packages I use as well

**Comment by matthewp** [comment] 2018-12-28 16:06
cc @balupton how can we help with this?

**Comment by mfasman95** [comment] 2018-12-28 16:39
I have also encountered this error.

**Comment by balupton** [comment] 2018-12-28 16:40
just spotted this

**Comment by balupton** [comment] 2018-12-28 16:41
looking into it

**Comment by balupton** [comment] 2018-12-28 16:43
if others can look into it too, that would be appreciated

what node verison, and what npm version are people using?

**Comment by yesmeck** [comment] 2018-12-28 16:46
```
[0] % node -v
v10.5.0
[0] % yarn -v
1.12.0
```

**Comment by balupton** [comment] 2018-12-28 16:46
Would someone be able to do this for me:

```
cd ./node_modules/errlop
node -e 'console.log(require("editions"))'
```

**Comment by mfasman95** [comment] 2018-12-28 16:46
I encountered this issue on Node 10.13.0 with NPM 6.4.1.

I noticed [this version bump](https://github.com/bevry/errlop/commit/c661d5634408e1c90853ec1720a63395d78a22a8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R108) in what appears to be the most recent commit with significant changes (from ~2 hours ago). Was there an API change with the `editions` library moving to version 2.x?

**Comment by yesmeck** [comment] 2018-12-28 16:47
Same error:

```
[0] % node -e 'console.log(require("editions"))'

/Users/meck/Workspace/app/node_modules/errlop/index.js:4
module.exports = require('editions').requirePackage(__dirname, require)
                                     ^

TypeError: require(...).requirePackage is not a function
    at Object.<anonymous> (/Users/meck/Workspace/app/node_modules/errlop/index.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/meck/Workspace/dchain-frontend/node_modules/editions/edition-node-0.8/index.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)

```

**Comment by mfasman95** [comment] 2018-12-28 16:47
I saw the same as @yesmeck

**Comment by balupton** [comment] 2018-12-28 16:48
> I noticed [this version bump](https://github.com/bevry/errlop/commit/c661d5634408e1c90853ec1720a63395d78a22a8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R108) in what appears to be the most recent commit with significant changes (from ~2 hours ago). Was there an API change with the `editions` library moving to version 2.x?

two changes:

1. editions v2 has internal changes, no API changes
2. editions v2 now uses errlop within it

**Comment by yesmeck** [comment] 2018-12-28 16:49
I guess the reason is the circular dependencies.

**Comment by yesmeck** [comment] 2018-12-28 16:49
`errlop` and `editions` are depending on each other.

**Comment by balupton** [comment] 2018-12-28 16:51
> `errlop` and `editions` are depending on each other.

circular dependencies have been supported in npm since I think v2 or v3

I also can't seem to reproduce this on my end

**Comment by balupton** [comment] 2018-12-28 16:52
I've setup https://github.com/balupton/errlop-issue-2 which works fine for me

Can someone setup a repo that fails

**Comment by yesmeck** [comment] 2018-12-28 16:57
You can try running the tests of https://github.com/bevry/istextorbinary, they also failed with the above error.

**Comment by kostaspt** [comment] 2018-12-28 16:58
@balupton Your repo works fine for me too, but running `npx oclif multi mynewcli` is failing.

![image](https://user-images.githubusercontent.com/684680/50522228-8c041b00-0ad2-11e9-8dec-406cd740e4a9.png)

**Comment by mfasman95** [comment] 2018-12-28 16:58
I just traced down the dependency chain for my project.
`yeoman-generator@4.1.1 -> istextorbinary@2.3.0 -> editions@2.1.0 -> errlop@1.1.0 -> editions@2.1.0 -> (loop)`

**Comment by balupton** [comment] 2018-12-28 17:03
interesting

- is there anyone on macos who it is failing for?
- is there anyone on windows who it is working for?

**Comment by mfasman95** [comment] 2018-12-28 17:03
I am on macos

**Comment by balupton** [comment] 2018-12-28 17:03
well there goes that

**Comment by mfasman95** [comment] 2018-12-28 17:10
I just made a fresh package to test something.

```json
{
  "name": "temp",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "istextorbinary": "^2.3.0"
  }
}
```
```js
const istextorbinary = require('istextorbinary');

console.log(istextorbinary('hello world'));
```

I got the same error on two node versions:
Node 8.11.3 - NPM 5.6.0
Node 10.13.0 - NPM 6.4.1

**Comment by balupton** [comment] 2018-12-28 17:12
working on a release of editions right now that skips errlop's dependency on it, and release new versions for both

perhaps this is happening because there are multiple `editions` v2 versions being installed at the same time

can someone gist their `package-lock.json`

**Comment by mfasman95** [comment] 2018-12-28 17:15
yarn.lock
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


binaryextensions@^2.1.2:
  version "2.1.2"
  resolved "{HOSTED_NPM}/binaryextensions/-/binaryextensions-2.1.2.tgz#c83c3d74233ba7674e4f313cb2a2b70f54e94b7c"
  integrity sha1-yDw9dCM7p2dOTzE8sqK3D1TpS3w=

editions@^2.0.2, editions@^2.1.0:
  version "2.1.0"
  resolved "{HOSTED_NPM}/editions/-/editions-2.1.0.tgz#5c6f6341ef19ee362a3bcbb907fe68e696dbc69e"
  integrity sha1-XG9jQe8Z7jYqO8u5B/5o5pbbxp4=
  dependencies:
    errlop "^1.0.3"
    semver "^5.6.0"

errlop@^1.0.3:
  version "1.1.0"
  resolved "{HOSTED_NPM}/errlop/-/errlop-1.1.0.tgz#34da3df1fc595585c94cb67c178d694da24470de"
  integrity sha1-NNo98fxZVYXJTLZ8F41pTaJEcN4=
  dependencies:
    editions "^2.1.0"

istextorbinary@^2.3.0:
  version "2.3.0"
  resolved "{HOSTED_NPM}/istextorbinary/-/istextorbinary-2.3.0.tgz#29458d7b10edcb52f4db9c57945bb67cd20cc4fd"
  integrity sha1-KUWNexDty1L025xXlFu2fNIMxP0=
  dependencies:
    binaryextensions "^2.1.2"
    editions "^2.0.2"
    textextensions "^2.4.0"

semver@^5.6.0:
  version "5.6.0"
  resolved "{HOSTED_NPM}/semver/-/semver-5.6.0.tgz#7e74256fbaa49c75aa7c7a205cc22799cac80004"
  integrity sha1-fnQlb7qknHWqfHogXMInmcrIAAQ=

textextensions@^2.4.0:
  version "2.4.0"
  resolved "{HOSTED_NPM}/textextensions/-/textextensions-2.4.0.tgz#6a143a985464384cc2cff11aea448cd5b018e72b"
  integrity sha1-ahQ6mFRkOEzCz/Ea6kSM1bAY5ys=
```

**Comment by balupton** [comment] 2018-12-28 17:33
okay, been able to reproduce

**Comment by ylecuyer** [comment] 2018-12-28 17:45
YOLO package updating XD

**Comment by balupton** [comment] 2018-12-28 17:47
alright, try `rm -rf node_modules package-lock.json yarn.lock` then `npm install` and cross your fingers with me

**Comment by kostaspt** [comment] 2018-12-28 17:55
Works for me now, thanks!

**Comment by mfasman95** [comment] 2018-12-28 18:04
Worked for me as well. Thank you!

**Comment by matthewp** [comment] 2018-12-28 18:08
@balupton 👏 you are amazing. Thanks for spending time on this.

**Comment by balupton** [comment] 2018-12-28 18:11
fantastic, thanks everyone for the speedy reports, you were all a fantastic help in debugging this, good work. I'm off to bed! Happy holidays

**Closed by balupton** 2018-12-28 18:11 UTC
